### ISSUE TITLE
Changes are not saved after editing profile in profile page

### ISSUE THREAD

**Issue by colen81** [hrishikeshpaul/noq#23]
- Click edit profile

- Edit some information

- Click "edit" (needs to be renamed to "save") 

- Information is not retained upon refresh

**Comment by hrishikeshpaul** [comment]
hey, this works for me!

**Comment by harishmaruthi** [comment]
Make sure to update instance details too!!
If needed, point out the branch and head of the branch (last commit).
Also, if it is local environment, there might be few unstashed changes which may result in such issues.
