### ISSUE TITLE
Changes to the profile page

### ISSUE THREAD

**Issue by hrishikeshpaul** [hrishikeshpaul/noq#9]
- [x] Implement Profile Picture Functionality
- [x] Make the jobs, education, experiences collapse-able 
- [x] Change acceptances to **Interests** ( think of an apt name as interests sound like hobbies or something)
- [x] Change display date format from YY to YYYY
- [x] Merge degree with field of study
- [x] Add colors to the page
- [x] Add **Rewards**, **Certifications** Tabs
- [x] Bigger font size for skills

**Comment by colen81** [comment]
All issues have been addressed.
